### ISSUE TITLE
Support php 8.0.0

### ISSUE THREAD

**Issue by julienbourgainpro** [laradock/laradock#2781]
**Describe the solution you'd like**

It would be awesome to support php 8.0.0 ! 

thanks a lot !

**Comment by deviouspk** [comment]
Don't forget xdebug 3.0 ;)

**Comment by kilvn** [comment]
Looking forward to it! ! !

**Comment by yusufonur** [comment]
Waiting impatiently.

**Comment by Mailzas** [comment]
Yes me too. Tried rename phpini7.4 to phpini8.0, and change version, but did not worked :(.

**Comment by maksimtvg** [comment]
> Yes me too. Tried rename phpini7.4 to phpini8.0, and change version, but did not worked :(.
Problem is in "FROM laradock/workspace:${BASE_IMAGE_TAG_PREFIX}-${LARADOCK_PHP_VERSION}"

there is no laradock/workspace:latest-8.0
and I couldn't install php8.0-zip extension

**Comment by lionslair** [comment]
Some point I was thinking of implementing this on my copy so 8 can run multiple or switch between. I use one setup for all projects.

https://medium.com/@msirius/1-n-php-versions-and-projects-via-laradock-51938b337071

**Comment by Mailzas** [comment]
> there is no laradock/workspace:latest-8.0
> and I couldn't install php8.0-zip extension

I was able to install php8, from official source, redirect php scripts to it, but was unable install mysqli extension to it. Maybe will try sometime later once more time.

**Comment by daryledesilva** [comment]
should be resolved by now

just switch to `PHP_VERSION=8.0` in your .env file

references:
- https://github.com/laradock/workspace/pull/36/files
- https://cyrildewit.github.io/2020/04/19/how-to-change-the-PHP-version-in-Laradock/
- https://hub.docker.com/layers/laradock/workspace/latest-8.0/images/sha256-3473d0b3e45a4048ec3b24d1c80178f976e877fead94a036f019804493410c4e?context=explore

**Comment by daryledesilva** [comment]
> Don't forget xdebug 3.0 ;)

@deviouspk @julienbourgainpro  had to solve this eventually for my case, something i came up with:
- https://github.com/laradock/laradock/pull/2818

which let's me finally use xdebug 3 + phpstorm + php 8 + laradock
but can't figure out yet how to get rid of the annoying error yet:
```
ERR: Could not connect to debugging client. Tried: host.docker.internal:9003 (through xdebug.client_host/xdebug.client_port) :-(
```

**Comment by Jedliu** [comment]
Is php8 officially supported or is any progress? Thanks,

**Comment by AdrienGiboire** [comment]
@Jedliu PHP 8.0 is supported but there is still some issues when installing Xdebug. It does not seem to be related to Xdebug per se. 

Although I still get [this issue](https://github.com/laradock/laradock/pull/2818#issuecomment-762566035), it manages to install on the condition I make 2 edits.

in `workspace/Dockerfile`, line 636:

```
RUN if [ ${INSTALL_AST} = true ]; then \
```
becomes
```
RUN if [ $[INSTALL_AST] = true ]; then \
```

in `php-fpm/Dockerfile`, line 688:

```
RUN if [ ${INSTALL_IMAGEMAGICK} = true ]; then \
```
becomes
```
RUN if [ $[INSTALL_IMAGEMAGICK] = true ]; then \
```

I don't understand why I had to do that, what are the potential side effects if any but I'm sharing.

**Comment by jn-jairo** [comment]
> @Jedliu PHP 8.0 is supported but there is still some issues when installing Xdebug. It does not seem to be related to Xdebug per se.
> 
> Although I still get [this issue](https://github.com/laradock/laradock/pull/2818#issuecomment-762566035), it manages to install on the condition I make 2 edits.
> 
> in `workspace/Dockerfile`, line 636:
> 
> ```
> RUN if [ ${INSTALL_AST} = true ]; then \
> ```
> 
> becomes
> 
> ```
> RUN if [ $[INSTALL_AST] = true ]; then \
> ```
> 
> in `php-fpm/Dockerfile`, line 688:
> 
> ```
> RUN if [ ${INSTALL_IMAGEMAGICK} = true ]; then \
> ```
> 
> becomes
> 
> ```
> RUN if [ $[INSTALL_IMAGEMAGICK] = true ]; then \
> ```
> 
> I don't understand why I had to do that, what are the potential side effects if any but I'm sharing. And considering the type of edits I had to do, I think depending on your `.env`, you might have more or less.
> 
> For example, if you do not wish to install AST (i.e. `WORKSPACE_INSTALL_AST` is set to `false`) in `.env`, I suspect you can get rid of the first edit I mentioned.

@AdrienGiboire You just turned it to false because:

- `${}` parameter expansion
- `$[]` deprecated syntax for arithmetic expansion, replaced by `$(())`

You can see more here https://stackoverflow.com/a/17992896

So instead of getting the variable value you did a arithmetic operation that returns 0, therefore didn't try to install ast/imagemagick.

**Comment by AdrienGiboire** [comment]
OK, thanks for the explanation @jn-jairo ! 🙌

**Comment by PavelSavushkinMix** [comment]
> should be resolved by now
> 
> just switch to `PHP_VERSION=8.0` in your .env file
> and for now, at least for my `.env`, i had to make the following changes (flipped from `true` to `false`):
> 
> ```
> #WORKSPACE_INSTALL_XDEBUG=true ### won't work with php8
> #WORKSPACE_INSTALL_IMAGEMAGICK=true ### won't work with php8
> #WORKSPACE_INSTALL_AST=true ### won't work with php8
> #PHP_FPM_INSTALL_IMAGEMAGICK=true   ### won't work with php8
> #PHP_FPM_INSTALL_XDEBUG=true ### won't work with php8
> ```
> 
> got it to work:
> 
> ```
> root@15eb1f83a9da:/var/www# php -v
> PHP 8.0.0 (cli) (built: Nov 27 2020 12:26:05) ( NTS )
> Copyright (c) The PHP Group
> Zend Engine v4.0.0-dev, Copyright (c) Zend Technologies
>     with Zend OPcache v8.0.0, Copyright (c), by Zend Technologies
> ```
> 
> references:
> 
> * https://github.com/laradock/workspace/pull/36/files
> * https://cyrildewit.github.io/2020/04/19/how-to-change-the-PHP-version-in-Laradock/
> * https://hub.docker.com/layers/laradock/workspace/latest-8.0/images/sha256-3473d0b3e45a4048ec3b24d1c80178f976e877fead94a036f019804493410c4e?context=explore

[AST's issue](https://github.com/laradock/laradock/issues/2859) -> [PR](https://github.com/laradock/laradock/pull/2860)

**Comment by PavelSavushkinMix** [comment]
[ImageMagick's issue](https://github.com/laradock/laradock/issues/2861) -> [PR](https://github.com/laradock/laradock/pull/2862)

**Comment by PavelSavushkinMix** [comment]
[CI support for PHP 8.0 issue](https://github.com/laradock/laradock/issues/2863) -> [PR](https://github.com/laradock/laradock/pull/2864)

**Comment by fredsal** [comment]
Where is php8.0.ini?

**Comment by shenders13** [comment]
Hi all,

This recently stopped working with PHP 8.

In `laradock/.env`, I have:

```
PHP_VERSION=8.0
```

In November, this command was working `docker-compose build --no-cache nginx php-fpm workspace`.

However, now we get:

```
 => ERROR [  5/113] RUN set -xe;     apt-get update -yqq &&     pecl channel-update pecl.php.net &&     groupadd -g 1000 laradock &&     useradd -u 1000 -g laradock -m l  2.8s
------                                                                                                                                                                          
 > [  5/113] RUN set -xe;     apt-get update -yqq &&     pecl channel-update pecl.php.net &&     groupadd -g 1000 laradock &&     useradd -u 1000 -g laradock -m laradock -G docker_env &&     usermod -p "*" laradock -s /bin/bash &&     apt-get install -yqq       apt-utils       libzip-dev zip unzip       php8.0-zip       nasm &&       php -m | grep -q 'zip':                                                                                                                                                                         
#9 0.206 + apt-get update -yqq
#9 2.742 + pecl channel-update pecl.php.net
#9 2.763 PHP Warning:  foreach() argument must be of type array|object, null given in /usr/share/php/PEAR/Command.php on line 249
```

I have reproduced this on two machines. Is there a workaround?

**Comment by lionslair** [comment]
> Hi all,
> 
> This recently stopped working with PHP 8.
> 
> In `laradock/.env`, I have:
> 
> ```
> PHP_VERSION=8.0
> ```
> 
> In November, this command was working `docker-compose build --no-cache nginx php-fpm workspace`.
> 
> However, now we get:
> 
> ```
>  => ERROR [  5/113] RUN set -xe;     apt-get update -yqq &&     pecl channel-update pecl.php.net &&     groupadd -g 1000 laradock &&     useradd -u 1000 -g laradock -m l  2.8s
> ------                                                                                                                                                                          
>  > [  5/113] RUN set -xe;     apt-get update -yqq &&     pecl channel-update pecl.php.net &&     groupadd -g 1000 laradock &&     useradd -u 1000 -g laradock -m laradock -G docker_env &&     usermod -p "*" laradock -s /bin/bash &&     apt-get install -yqq       apt-utils       libzip-dev zip unzip       php8.0-zip       nasm &&       php -m | grep -q 'zip':                                                                                                                                                                         
> #9 0.206 + apt-get update -yqq
> #9 2.742 + pecl channel-update pecl.php.net
> #9 2.763 PHP Warning:  foreach() argument must be of type array|object, null given in /usr/share/php/PEAR/Command.php on line 249
> ```
> 
> I have reproduced this on two machines. Is there a workaround?
> 
> **UPDATE:**
> 
> The fix was to go into `laradock/workspace/Dockerfile` and update `BASE_IMAGE_TAG_PREFIX` to:
> 
> ```
> ARG BASE_IMAGE_TAG_PREFIX='20211218'
> ```
> 
> By the looks of things, the latest docker image doesn't work.
> 
> Thanks @silverjason

Try this base image. Worked for me last week WORKSPACE_BASE_IMAGE_TAG_PREFIX=20220115

**Comment by askibski-alison** [comment]
I confirm, that, if you have problems with workspace, try not to user WORKSPACE_BASE_IMAGE_TAG_PREFIX=latest and use 20220115 for example. I hope image will be fixed one day, so you will be able to switchback to the latest one in future :)
