### ISSUE TITLE
Problem on apt-get update

### ISSUE THREAD

**Issue by cabrerabywaters** [LaraDock/laradock#53]
Hello there Mahmoud!

I'm having an issue while trying to set up Laradock.

When I do a 
`docker-compose up -d  nginx mysql redis workspace`

I'm getting an error on the apt-get update command on line 15 of the Workspace Dockerfile.

> W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/main/source/Sources  Hash Sum mismatch

I tried running 
`rm /var/lib/apt/lists/* -vf`
in the Dockerfile before the update, but I'm still getting the same error.

![screen shot 2016-05-18 at 8 42 02 pm](https://cloud.githubusercontent.com/assets/3051507/15378339/0abd825e-1d39-11e6-968f-b31328e7bb0c.png)

Any ideas?

**Comment by Mahmoudz** [comment]
Hi, I rebuilt the Workspace container twice on my machine and one once a Vagrant machine, and wasn't able to reproduce that error.
What I advice is to this:
1. Pull the latest version: `git pull origin master` now it's `2.2.0`
2 . Remove the workspace images and any `<none>` images with `docker rmi {container-id}`
3 . Rebuild the workspace `docker-compose build --no-cache workspace`
4 . Try again `docker-compose up -d nginx mysql redis workspace`

**Comment by cabrerabywaters** [comment]
Thank you Mahmoud, it worked!docker-machine l.

I think that maybe doing the 

`git submodule add https://github.com/LaraDock/laradock.git`

as written in the Readme, did not pull the latest version of the repo

**Comment by Mahmoudz** [comment]
@cabrerabywaters it does actually but before answering your question I released new version was working on.
Best,

**Comment by matriphe** [comment]
Found the same problem. Running on OSX 10.11.4, using Docker Toolbox (Kitematic) version 0.10.2 that runs docker version 1.11.1 and docker-machine version 0.7.0.

Have tried to run the suggested step, but it's failed on `docker-compose build --no-cache workspace`

The error:
```
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/universe/binary-amd64/Packages  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.
ERROR: Service 'workspace' failed to build: The command '/bin/sh -c apt-get update && apt-get install -y     software-properties-common' returned a non-zero code: 100
```

**Comment by Mahmoudz** [comment]
I think you just need to delete all the workspace containers and the workspace images and try again it will rebuild the workspace but in the next attempt it might not face any problem with the connection while running `apt-get`.

**Comment by matriphe** [comment]
I found image named `laradock_application` and then delete it using `docker rmi` command.

Then I run `docker-compose build --no-cache workspace` and it failed, and the error is still occured. Here the full output, I think it will help.
```
bash-3.2$ docker images
REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
laradock_application          latest              a6d68920536a        10 hours ago        125.1 MB
centos                        latest              8596123a638e        4 days ago          196.7 MB
ubuntu                        latest              c5f1cf30c96b        2 weeks ago         120.8 MB
percona                       latest              4e17d4db0a84        9 weeks ago         309.4 MB
centos                        7                   ed38e4ac7e1b        5 months ago        194.7 MB
phusion/baseimage             latest              772dd063a060        5 months ago        305.2 MB
nginx                         latest              9f3d4c9acb57        6 months ago        132.7 MB
mysql                         latest              60dbc2f8949d        6 months ago        359.8 MB
debian                        jessie              39a8a358844a        6 months ago        125.1 MB
ubuntu-upstart                latest              dc531b4cb86a        6 months ago        253.1 MB
busybox                       latest              aa5d5f5a81c9        6 months ago        1.109 MB
alpine                        latest              558af09712a4        8 months ago        5.244 MB
bash-3.2$ docker rmi -f a6d68920536a
Untagged: laradock_application:latest
Deleted: sha256:a6d68920536a6f883bf60f1cb70ef5c8a54b0e1b5150341128fd879fe23f7ecd
Deleted: sha256:f583b1c638c5a94e83070f649b054723300ec1ec83a4f56100eaeb4116ba62ba
Deleted: sha256:00ac90e68bf4e66402a159e79dc72f56bc8efcb10b867cc7282d706d6a647113
Deleted: sha256:f55cc2c318ab9d0beb9d7666cfa45e7d7793a8ea8fee1dc64c60f8f9f12783f6
bash-3.2$ docker images
REPOSITORY                    TAG                 IMAGE ID            CREATED             SIZE
centos                        latest              8596123a638e        4 days ago          196.7 MB
ubuntu                        latest              c5f1cf30c96b        2 weeks ago         120.8 MB
percona                       latest              4e17d4db0a84        9 weeks ago         309.4 MB
centos                        7                   ed38e4ac7e1b        5 months ago        194.7 MB
phusion/baseimage             latest              772dd063a060        5 months ago        305.2 MB
nginx                         latest              9f3d4c9acb57        6 months ago        132.7 MB
mysql                         latest              60dbc2f8949d        6 months ago        359.8 MB
debian                        jessie              39a8a358844a        6 months ago        125.1 MB
ubuntu-upstart                latest              dc531b4cb86a        6 months ago        253.1 MB
busybox                       latest              aa5d5f5a81c9        6 months ago        1.109 MB
alpine                        latest              558af09712a4        8 months ago        5.244 MB
bash-3.2$ docker-compose build --no-cache workspace
Building workspace
Step 1 : FROM phusion/baseimage:latest
 ---> 772dd063a060
Step 2 : MAINTAINER Mahmoud Zalt <mahmoud@zalt.me>
 ---> Running in aa25bd19d6d6
 ---> 1abe07b303e5
Removing intermediate container aa25bd19d6d6
Step 3 : RUN DEBIAN_FRONTEND=noninteractive
 ---> Running in 8d5b9f921431
 ---> 3e2fe99dcf73
Removing intermediate container 8d5b9f921431
Step 4 : RUN locale-gen en_US.UTF-8
 ---> Running in 9cfc5051e98b
Generating locales...
  en_US.UTF-8... up-to-date
Generation complete.
 ---> e4adaea2d3f4
Removing intermediate container 9cfc5051e98b
Step 5 : ENV LANGUAGE en_US.UTF-8
 ---> Running in 39de5e322d47
 ---> cbee9159bb37
Removing intermediate container 39de5e322d47
Step 6 : ENV LC_ALL en_US.UTF-8
 ---> Running in 801854c62f62
 ---> c2a6e3ce8223
Removing intermediate container 801854c62f62
Step 7 : ENV LC_CTYPE UTF-8
 ---> Running in 788388801e8b
 ---> c1292cd9f229
Removing intermediate container 788388801e8b
Step 8 : ENV LANG en_US.UTF-8
 ---> Running in 0bcbbf7f75ea
 ---> 1c3a17bead00
Removing intermediate container 0bcbbf7f75ea
Step 9 : ENV TERM xterm
 ---> Running in 1614a3a09bbb
 ---> f9b5eae99093
Removing intermediate container 1614a3a09bbb
Step 10 : RUN apt-get update && apt-get install -y     software-properties-common
 ---> Running in 42a5b8094b52
Ign http://archive.ubuntu.com trusty InRelease
Get:1 http://archive.ubuntu.com trusty-updates InRelease [65.9 kB]
Get:2 http://archive.ubuntu.com trusty-security InRelease [65.9 kB]
Get:3 http://archive.ubuntu.com trusty Release.gpg [933 B]
Get:4 http://archive.ubuntu.com trusty Release [58.5 kB]
Get:5 http://archive.ubuntu.com trusty-updates/main Sources [346 kB]
Get:6 http://archive.ubuntu.com trusty-updates/restricted Sources [5,217 B]
Get:7 http://archive.ubuntu.com trusty-updates/universe Sources [194 kB]
Get:8 http://archive.ubuntu.com trusty-updates/main amd64 Packages [964 kB]
Get:9 http://archive.ubuntu.com trusty-updates/restricted amd64 Packages [23.5 kB]
Get:10 http://archive.ubuntu.com trusty-updates/universe amd64 Packages [464 kB]
Get:11 http://archive.ubuntu.com trusty-security/main Sources [147 kB]
Get:12 http://archive.ubuntu.com trusty-security/restricted Sources [3,920 B]
Get:13 http://archive.ubuntu.com trusty-security/universe Sources [41.8 kB]
Get:14 http://archive.ubuntu.com trusty-security/multiverse Sources [2,547 B]
Get:15 http://archive.ubuntu.com trusty-security/main amd64 Packages [602 kB]
Get:16 http://archive.ubuntu.com trusty-security/restricted amd64 Packages [20.2 kB]
Get:17 http://archive.ubuntu.com trusty-security/universe amd64 Packages [167 kB]
Get:18 http://archive.ubuntu.com trusty-security/multiverse amd64 Packages [4,853 B]
Get:19 http://archive.ubuntu.com trusty/main Sources [1,335 kB]
Get:20 http://archive.ubuntu.com trusty/restricted Sources [5,335 B]
Get:21 http://archive.ubuntu.com trusty/universe Sources [7,926 kB]
Get:22 http://archive.ubuntu.com trusty/main amd64 Packages [1,743 kB]
Get:23 http://archive.ubuntu.com trusty/restricted amd64 Packages [16.0 kB]
Get:24 http://archive.ubuntu.com trusty/universe amd64 Packages [7,589 kB]
Fetched 21.8 MB in 1min 2s (350 kB/s)
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/universe/binary-amd64/Packages  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.
ERROR: Service 'workspace' failed to build: The command '/bin/sh -c apt-get update && apt-get install -y     software-properties-common' returned a non-zero code: 100
bash-3.2$ 
```

**Comment by matriphe** [comment]
been looking for this situation, and i found similar bug in Ubuntu Trusty. https://github.com/docker-library/official-images/issues/1350

I've tried to barely build from the `workspace/Dockerfile` and got same error. replacing `phusion/baseimage` to `ubuntu:trusty` didn't resolve the issue.

But, when I change the base image of `workspace/Dockerfile` to `ubuntu:latest` (xenial), it's worked like a charm. I don't know it's issue from the Ubuntu Trusty or not.

**Comment by matriphe** [comment]
I tried using `sunfoxcz/baseimage:latest` for the base image. it's based on `phuson/baseimage` but use Ubuntu Xenial. it's worked.

**Comment by atefBB** [comment]
This [solution](https://robinwinslow.uk/fix-docker-networking-dns) works for me !
