### ISSUE TITLE
Running docker-compose exec workspace bash command on Windows env shows an error

### ISSUE THREAD

**Issue by kvahuja** [laradock/laradock#563]
My workspace:
 - Windows 10
 - Docker version: 1.13.0 (9795)
 - Channel: Stable

after I am done with docker-compose up command i fire the following command to get to my shell..

```
docker-compose exec workspace bash
```

Then the command finishes, I am logged into the Shell but i get the following error as well...

```
bash: $'\r': command not found
bash: $'\r': command not found
bash: $'\r': command not found
bash: $'\r': command not found
bash: $'\r': command not found
bash: $'\r': command not found
bash: $'\r': command not found
bash: $'\r': command not found
bash: $'\r': command not found
bash: $'\r': command not found
bash: $'\r': command not found
bash: /home/laradock/aliases.sh: line 61: syntax error near unexpected token `$'{\r''
'ash: /home/laradock/aliases.sh: line 61: `function mkd() {
```

p.s.: I will try to fix the shell via PR, but want to record it.

**Comment by philtrep** [comment]
@mikeerickson I believe that's from #557

**Comment by azamatsulaiman** [comment]
same error for me

**Comment by bagart** [comment]
is not 'just same'

1.
```
/home/laradock/aliases.sh: line 2: $'\r': command not found
```
FIX:
```
sed -i 's/\r//' /home/laradock/aliases.sh
```

2. 
```#! /bin/sh
function mkd() {
    mkdir -p "$@" && cd "$@"
}
```
sh not work firh func!

FIX:
```
sed -i 's/^#! \/bin\/sh/#! \/bin\/bash/' /home/laradock/aliases.sh
```

**Comment by philtrep** [comment]
Fixed by PR #580

**Comment by kvahuja** [comment]
does this require a full rebuild of all containers? (i would presume yes).

**Comment by bagart** [comment]
Yes. Need rebuild workspace image for copy
/home/laradock/aliases.sh

Or just run 2 sed command ^^^

**Comment by kvahuja** [comment]
i just rebuilt the workspace container and the error still comes when i login with root or laradock.

am i doing something wrong?

**Comment by bagart** [comment]
What about error message? :)))

**Comment by kvahuja** [comment]
the error message still pops up for both root and laradock users, exactly as it was before.

**Comment by bagart** [comment]
```
docker-compose stop
git pull
docker-compose build --pull workspace
```

**Comment by kvahuja** [comment]
I went ahead and tested this on Linux (Ubuntu 14.04 to be precise) and it works fine. the problem I had was on Docker for Windows and the problem on Windows still exists.

from my original post here are the environment details:

> My workspace:

Windows 10
Docker version: 1.13.0 (9795)
Channel: Stable


@bagart  - I would like to reopen this, but i will let you be decide that one.

**Comment by bagart** [comment]
```
docker-compose build --pull workspace 

```

sorry. this is not force rebuild (if image is not updated)
for check create any file in /home/laradock
```
touch /home/laradock/123
```
try to delete and rebuild
```
docker-compose stop workspace 
docker-compose rm workspace 
docker-compose up -d workspace 
```

or delete it with Kitematic (Alpha)
![image](https://cloud.githubusercontent.com/assets/2109022/22884004/c31f275e-f203-11e6-9849-1e1e13f7f726.png)



and after check  for file exists

```
ls /home/laradock/123
```

and 1 more thing:
```
bash: $'\r': command not found
```
I not sure about file of script with this error.
it's need to check with some debug and log
```
$ docker logs laradock_workspace_1
```
or other

**Comment by kvahuja** [comment]
thanks for the pointer on SED. 

Old Section for alias.sh
``` shell
#####################################
# User Aliases
#####################################

USER laradock
COPY ./aliases.sh /home/laradock/aliases.sh
RUN echo "" >> ~/.bashrc && \
    echo "# Load Custom Aliases" >> ~/.bashrc && \
    echo "source /home/laradock/aliases.sh" >> ~/.bashrc && \
    echo "" >> ~/.bashrc 
 
USER root
RUN echo "" >> ~/.bashrc && \
    echo "# Load Custom Aliases" >> ~/.bashrc && \
    echo "source /home/laradock/aliases.sh" >> ~/.bashrc && \
    echo "" >> ~/.bashrc
```


replaced with following by adding the SED commands and my problem went away. not sure if you classify this as a bug in the Dockerfile. 

P.S.: I haven't tested this on Ubuntu or other Linux environment (i don't have one).

``` shell
#####################################
# User Aliases
#####################################

USER laradock
COPY ./aliases.sh /home/laradock/aliases.sh
RUN echo "" >> ~/.bashrc && \
    echo "# Load Custom Aliases" >> ~/.bashrc && \
    echo "source /home/laradock/aliases.sh" >> ~/.bashrc && \
    echo "" >> ~/.bashrc && \
    sed -i 's/\r//' /home/laradock/aliases.sh && \
    sed -i 's/^#! \/bin\/sh/#! \/bin\/bash/' /home/laradock/aliases.sh
    
USER root
RUN echo "" >> ~/.bashrc && \
    echo "# Load Custom Aliases" >> ~/.bashrc && \
    echo "source /home/laradock/aliases.sh" >> ~/.bashrc && \
    echo "" >> ~/.bashrc && \
    sed -i 's/\r//' /home/laradock/aliases.sh && \
    sed -i 's/^#! \/bin\/sh/#! \/bin\/bash/' /home/laradock/aliases.sh
```

**Comment by NisalG** [comment]
This is what worked for me:
Replace laradock/workspace/Dockerfile > 'User Alias' section according to @kvahuja 

Rebuilt according to @bagart:
`$ docker-compose stop`
`$ git pull`
`$ docker-compose build --pull workspace`
`$ docker-compose up -d nginx mysql`
`$ docker-compose exec workspace bash`

**Comment by bagart** [comment]
yes - that command rebuild new workspace image
but not clear(rebuild) docker image workspace
how make it? my last comment about it

**Comment by MeiRct** [comment]
@philtrep Wouldn't it be better to add the "sed" command which removes the `\r` instances to the _workspace/Dockerfile-*_ files? (Dockerfile-56, Dockerfile-70, Dockerfile-71)

**Comment by bagart** [comment]
for correct use without "\r" you need configure git on windows(or make correct choice on installation step)
"\r" must not present in git repo
PS: my fixes not for actual laradock version

**Comment by rogerroelofs** [comment]
Since rebuilding my workspace image recently I'm not getting carriage returns at the end of output.  I'm not sure if it is related to this change or not.  My output looks like this now.  I can make a separate issue if it turns out to be not related.  I"m on a mac with the most recently pulled laradock master.
```
root@8e12e1ec8d42:/var/www# echo "hi"
                                     hi
                                       root@8e12e1ec8d42:/var/www# exit
```
