### ISSUE TITLE
403 Forbidden - nginx error

### ISSUE THREAD

**Issue by shahzeb1** [laradock/laradock#878]
I have followed all instructions in the docs, but when I try to visit `localhost` it simply throws up a "403 Forbidden  - nginx" error.

Really weird because if I visit `http://localhost/public/css/app.css` I am able to see the default app.css contents which are included with the Laravel installation. Really not sure what is going on.

Would love some help.

Thank you.

**Comment by winfried-van-loon** [comment]
Hi there! We very recently changed something with the paths (#850), I think there is an issue in there. 

First of, could you check the Laradock `.env` file's application path? By default it should be:

```
APPLICATION=../public/
```

I can't seem to reproduce the issue in the nginx container. Could you try the following command to rebuild the containers if they need rebuilding and try if the issue is still there?

```
docker-compose up -d --force-recreate --build nginx
```

If the issue is still there, could you check if you've got the latest version of Laradock and if so, could you paste the command you're using to up the containers and the non-default settings of the Laradock `.env` file?

Thanks!

**Comment by shahzeb1** [comment]
### Some updates:

So I got the Laravel app (called "backend") to work on it's own (without Docker) on my local Macbook. Meaning, when I run `$ ./artisan serve` and visit `http://127.0.0.1:8000`, I can see the Laravel welcome page working just fine.

Since I am trying to get Laradock to work with an new project, I am using method [A2](http://laradock.io/getting-started/#A2). 

I still see this: 

![image](https://cloud.githubusercontent.com/assets/1383831/25572636/eeb4b076-2df1-11e7-8036-f020ed90995d.png)

And weirdly enough, I'm still able to view [app.css](http://localhost/public/css/app.css)' contents.

Here's what my `$ docker ps` looks like:

![image](https://cloud.githubusercontent.com/assets/1383831/25572656/1e77e6de-2df2-11e7-8f0a-3c04bea22c46.png)

**Comment by winfried-van-loon** [comment]
I think there's an issue in #850, will push a solution in about three to five hours from now. Thanks for reporting!

**Comment by shahzeb1** [comment]
@winfried-van-loon so you were able to re-create the bug? I'm not going crazy haha.

**Comment by winfried-van-loon** [comment]
Not yet, but I think I know how to resolve the problem either way. I think the webroot isn't correct. I would test it right now and push it but my macbook has ran out of power and there's no power outlet nearby. Will report back soon.

**Comment by winfried-van-loon** [comment]
Okay, those changes should fix it!

**Comment by winfried-van-loon** [comment]
If you've still got the issue, let us know! 👍

**Comment by shahzeb1** [comment]
Celebrations are in order! (It works) 🎉

**Comment by Caisen1988** [comment]
I still have the issur, pls help ,thanks a lot
### 1.file path
```
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        2018/3/25     21:18                code
d-----        2018/3/25     21:16                laradock
```
### 2. /laradock/.env
```
APPLICATION=../code/
```
###  /nginx/sites/
* remove .example
* add keyoutest.conf
> root /var/www/keyoutest;

### restart
```
docker-compose down
docker-compose exec workspace bash
```
### into the bash
```
composer create-project --prefer-dist laravel/laravel keyoutest "5.5.*"
```
### result
```
403 Forbidden for http://localhost
is ok for http://localhost/public/css/app.css
```

**Comment by Caisen1988** [comment]
finally find the reason ,it's nginx root path should  direct the laravel public folder,thanks a lot
```
 root   /var/www/html/site1/blog/public;
```

**Comment by RaptorialThing** [comment]
Thanks for solve issue. 18.12.2020. I install fresh laradock to VDS hosting by official docs. Then I install some laravel app by laradock docs. But I got same error "`403 nginx`".
 
The solution is check premissions to your installed laravel files. (ls -l your laravel app\public\index.html)

For me it was `laradock:laradock`. (because I did `docker-compose exec --user=laradock workspace` bash   and in container did `composer create some laravel projec`t) 
and in laradock/nginx/nginx.conf was "`user www-data`". 
So I run `docker-compose exec workspace bash` and change permissions
 "`sudo chown -R www-data:www-data /var/www/`".

Maybe that helps anyone.
